Update script

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -1,26 +1,44 @@
 {{ if eq .chezmoi.osRelease.id "ubuntu" -}}
 #!/bin/sh
+set -e
 sudo apt install git vim build-essential cmake python3-dev zsh
-git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
+git clone --depth=1 https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
+git clone --depth=1 https://github.com/ryanoasis/nerd-fonts.git
+cd nerd-fonts && ./install.sh Meslo
 vim +PluginInstall +qall
 cd ~/.vim/bundle/youcompleteme
 python3 install.py
 if hash zsh > /dev/null 2>&1 ; then
+	mv .zshrc .zshrc.bck
         sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
+	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
+	mv .zshrc.bck .zshrc
+	source .zshrc
 else
         echo "zsh command not found"
 fi
 {{ else if eq .chezmoi.osRelease.id "arch" -}}
 #!/bin/bash
+set -e
 sudo pacman -S git vim build-essential cmake python3-dev zsh zsh-completions curl
 git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
-vim +PluginInstall +qall
-cd ~/.vim/bundle/youcompleteme
-python3 install.py
+git clone https://aur.archlinux.org/yay.git
+cd yay
+makepkg -si
+if hash yay > /dev/null 2>&1 ; then
+	yay -S nerd-fonts-meslo 
+	vim +PluginInstall +qall
+	cd ~/.vim/bundle/youcompleteme
+	python3 install.py
+else
+	echo "yay command not found"
+fi
 if hash zsh > /dev/null 2>&1 ; then
+	mv .zshrc .zshrc.bck
         sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
+	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
+	mv .zshrc.bck .zshrc
+	source .zshrc
 else
         echo "zsh command not found"
 fi
